### ISSUE TITLE
There is not get from the config_db to the vif

### ISSUE THREAD

**Issue by sarit8** [WeiChungWu/UVM_UART_Example#2]

**Comment by sarit8** [comment]
There is no get in the config file.

**Comment by WeiChungWu** [comment]
What do you mean "no get"? Can you elaborate more?

**Comment by sarit8** [comment]
there  is no get form the config_db to the vif.

In addition in the monitor you execute the following in the bukid phase:
    super.build_phase(phase);
        uart_vif = cfg.uart_vif;

In the build phase the monitor don't "know" the gaent_host_config, and the uart_vif will be NULL.

**Comment by WeiChungWu** [comment]
`uart_host_config` will be set in `super.build_phase(phase)`. It won't be NULL.

**Comment by sarit8** [comment]
I use your code, and fill the blank parts, and I got NULL
